package types

import (
	"bytes"
	"log"
	"text/template"
	"time"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"google.golang.org/protobuf/compiler/protogen"
)

func header(gen *protogen.GeneratedFile, file *protogen.File) {
	gen.P("// Code generated by protoc-gen-go-cli. DO NOT EDIT.")
	gen.P("//", time.Now().Format(time.TimeOnly))
	gen.P()
	gen.P("package ", file.GoPackageName)
	gen.P()
}

var (
	title = cases.Title(language.English, cases.NoLower)
	lower = cases.Lower(language.English)
)

func executeTemplate(gen *protogen.GeneratedFile, tmpl *template.Template, data any) error {
	var buffer bytes.Buffer

	if err := tmpl.Execute(&buffer, data); err != nil {
		log.Println("failed to execute template", err)
		return err
	}

	_, err := gen.Write(buffer.Bytes())
	if err != nil {
		log.Println("failed to write", err)
	}

	return err
}
